sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t svkmsr6/docker-mc-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true svkmsr6/docker-mc-app npm test -- --coverage

after_success:
  - docker build -t svkmsr6/multi-client ./client
  - docker build -t svkmsr6/multi-nginx ./nginx
  - docker build -t svkmsr6/multi-server ./server
  - docker build -t svkmsr6/multi-worker ./worker
  #Login using Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take the images and push them to Dockerhub
  - docker push svkmsr6/multi-client
  - docker push svkmsr6/multi-nginx
  - docker push svkmsr6/multi-server
  - docker push svkmsr6/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker-m-app'
  env: 'Dockermapp-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-424035822307'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY